var GameContainer = document.getElementById("GameContainer");
console.log(GameContainer.getBoundingClientRect().width);
var r = new GRID.Renderer(GameContainer.clientWidth,GameContainer.clientHeight);
var b = new GRID.Board(9);
GameContainer.appendChild(r.domElement);
b.setColor("a","b","c");
b.randomColor(5);
b.addPiece(5);
console.log(b.piece);
r.render(b);